apiVersion: v1
kind: Service
metadata:
  name: k8s-reliability-demo-service
  namespace: devops-app
spec:
  selector:
    app: k8s-reliability-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: NodePort
